std="roblox+luau"
[rules]
unused_variable = "allow"
shadowing = "allow"
multiple_statements = "allow"
parenthese_conditions = "allow"
empty_if = "allow"
global_usage = "allow"
incorrect_standard_library_use = "allow"