name: Lint Canary

on:
  push:
    branches: [canary]

jobs: 
  lint: 
    name: Lint
    runs-on: ubuntu-latest
    steps: 
      - uses: actions/checkout@v2
        with:
          ref: canary
      - uses: Roblox/setup-foreman@v1
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
      - name: Lint
        run: selene ./MainModule